services:
  - type: web
    name: e-smart-wallet-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://e-smart-wallet.vercel.app
      - key: MONGO_URI
        fromDatabase:
          name: mongodb
          property: connectionString
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: JWT_EXPIRE
        value: 7d
      - key: COOKIE_EXPIRE
        value: 7